import { GROUND, NAV } from '../config/sim.js';
import { clamp, type Vec2 } from '../sim/math.js';
import type { Obstacle, Shape, WorldMap } from './types.js';

export type CollisionMask = 'move' | 'shots';

const HASH_CELL = 120;
/** Number of push-out passes. Two is enough to settle a unit wedged between two shapes. */
const RESOLVE_PASSES = 2;

export function shapeBounds(s: Shape): { x0: number; y0: number; x1: number; y1: number } {
  switch (s.type) {
    case 'circle':
      return { x0: s.x - s.r, y0: s.y - s.r, x1: s.x + s.r, y1: s.y + s.r };
    case 'capsule':
      return {
        x0: Math.min(s.ax, s.bx) - s.r,
        y0: Math.min(s.ay, s.by) - s.r,
        x1: Math.max(s.ax, s.bx) + s.r,
        y1: Math.max(s.ay, s.by) + s.r,
      };
    case 'box': {
      const e = Math.hypot(s.hw, s.hh);
      return { x0: s.x - e, y0: s.y - e, x1: s.x + e, y1: s.y + e };
    }
  }
}

/**
 * Signed-ish distance data for a point against a shape: the closest point on the shape surface and
 * whether the point is inside. Circles and capsules are handled as a core plus radius.
 */
function closest(s: Shape, px: number, py: number): { cx: number; cy: number; pad: number; inside: boolean } {
  if (s.type === 'circle') return { cx: s.x, cy: s.y, pad: s.r, inside: false };
  if (s.type === 'capsule') {
    const dx = s.bx - s.ax;
    const dy = s.by - s.ay;
    const len2 = dx * dx + dy * dy;
    const t = len2 === 0 ? 0 : clamp(((px - s.ax) * dx + (py - s.ay) * dy) / len2, 0, 1);
    return { cx: s.ax + dx * t, cy: s.ay + dy * t, pad: s.r, inside: false };
  }
  // Box: work in the box's local frame.
  const cos = Math.cos(-s.angle);
  const sin = Math.sin(-s.angle);
  const lx = (px - s.x) * cos - (py - s.y) * sin;
  const ly = (px - s.x) * sin + (py - s.y) * cos;
  const inside = Math.abs(lx) < s.hw && Math.abs(ly) < s.hh;
  let qx = clamp(lx, -s.hw, s.hw);
  let qy = clamp(ly, -s.hh, s.hh);
  if (inside) {
    // Push out through the nearest face.
    if (s.hw - Math.abs(lx) < s.hh - Math.abs(ly)) qx = Math.sign(lx || 1) * s.hw;
    else qy = Math.sign(ly || 1) * s.hh;
  }
  const c2 = Math.cos(s.angle);
  const s2 = Math.sin(s.angle);
  return { cx: s.x + qx * c2 - qy * s2, cy: s.y + qx * s2 + qy * c2, pad: 0, inside };
}

/** Whether a shape blocks a circle of `radius` at (x, y): the test `pointBlocked` makes per obstacle. */
export function shapeBlocks(s: Shape, x: number, y: number, radius: number): boolean {
  const c = closest(s, x, y);
  if (c.inside) return true;
  const reach = c.pad + radius;
  return (x - c.cx) ** 2 + (y - c.cy) ** 2 < reach * reach;
}

/**
 * Obstacles generated per chunk (world streaming step 3), on the streaming chunk grid. A chunk's
 * obstacles may reach up to `spill` units into its neighbours (a forest at a chunk edge), never further.
 */
export interface ChunkObstacleSource {
  readonly cols: number;
  readonly rows: number;
  readonly size: number;
  readonly spill: number;
  obstacles(cx: number, cy: number): readonly Obstacle[];
}

/**
 * Collision and navigation data for one map. Built once per map; the static spatial hash keeps
 * every query to the handful of obstacles near the point.
 *
 * A map generated by chunk (`source`) starts with only the zone plan's obstacles. A chunk's own
 * obstacles go into the hash, and its nav cells are worked out, the first time anything asks about
 * a point in it: a collision test, a line of sight, a path search or the room waking it. Its
 * neighbours' obstacles go in too, since they may reach into it. Every cell keeps its obstacles in
 * one fixed order (the plan's, then each chunk's in chunk order), so every answer is the same as on
 * the map built whole, whatever order the chunks were asked for in.
 */
export class GameMap {
  readonly width: number;
  readonly height: number;
  readonly navCols: number;
  readonly navRows: number;
  /** 1 where a nav cell is open. On a map built by chunk, cells of chunks not built yet read 0: ask `isWalkable`. */
  readonly walkable: Uint8Array;
  private readonly cols: number;
  private readonly rows: number;
  /** Obstacles per hash cell; a cell with none has no array, so a big empty map costs little. */
  private readonly grid: (Obstacle[] | undefined)[];
  /** Roads per hash cell. Every mover asks for its ground speed every tick, so no full scan. */
  private readonly roadGrid: (Shape[] | undefined)[];
  /** Per streaming chunk: 1 once its obstacles are in the hash, 2 once its nav cells are worked out too. */
  private readonly chunkState: Uint8Array | null;
  /** Where each obstacle sorts within a hash cell, on a map built by chunk. */
  private readonly order = new Map<Obstacle, number>();
  private chunksBuilt = 0;

  constructor(
    readonly def: WorldMap,
    private readonly source: ChunkObstacleSource | null = null,
  ) {
    this.width = def.width;
    this.height = def.height;
    this.cols = Math.ceil(def.width / HASH_CELL) + 1;
    this.rows = Math.ceil(def.height / HASH_CELL) + 1;
    this.grid = new Array<Obstacle[] | undefined>(this.cols * this.rows);
    this.roadGrid = new Array<Shape[] | undefined>(this.cols * this.rows);
    for (const [i, o] of def.obstacles.entries()) this.insert(o, i);
    for (const g of def.ground) {
      if (g.kind !== 'road') continue;
      this.forCells(g.shape, (i) => {
        const list = this.roadGrid[i];
        if (list) list.push(g.shape);
        else this.roadGrid[i] = [g.shape];
      });
    }

    const cell = NAV.cellSize;
    this.navCols = Math.ceil(def.width / cell);
    this.navRows = Math.ceil(def.height / cell);
    this.walkable = new Uint8Array(this.navCols * this.navRows);
    if (source) {
      // Nav cells must not straddle chunks, so a chunk's cells are exactly the ones inside it.
      if (source.size % cell !== 0 || source.spill >= source.size) throw new Error('chunk size must be a whole number of nav cells and wider than the spill');
      this.chunkState = new Uint8Array(source.cols * source.rows);
      return;
    }
    this.chunkState = null;
    this.fillWalkable(0, 0, this.navCols, this.navRows);
  }

  private fillWalkable(cx0: number, cy0: number, cx1: number, cy1: number): void {
    const cell = NAV.cellSize;
    for (let cy = cy0; cy < cy1; cy++) {
      for (let cx = cx0; cx < cx1; cx++) {
        const blocked = this.blockedNow((cx + 0.5) * cell, (cy + 0.5) * cell, NAV.agentRadius, 'move');
        this.walkable[cy * this.navCols + cx] = blocked ? 0 : 1;
      }
    }
  }

  /** Adds an obstacle to every hash cell it touches, keeping each cell in `rank` order. */
  private insert(o: Obstacle, rank: number): void {
    if (this.source) this.order.set(o, rank);
    this.forCells(o.shape, (i) => {
      const list = this.grid[i];
      if (!list) {
        this.grid[i] = [o];
        return;
      }
      let at = list.length;
      // Chunks arrive in any order; a cell's list stays sorted, usually by appending.
      while (at > 0 && (this.order.get(list[at - 1] ?? o) ?? 0) > rank) at--;
      list.splice(at, 0, o);
    });
  }

  /** How many chunks have been built, for tests and the bench. 0 on a map built whole. */
  get builtChunks(): number {
    return this.chunksBuilt;
  }

  /** Builds the chunk holding (x, y) if it is not built yet. */
  ensureChunk(cx: number, cy: number): void {
    const src = this.source;
    const state = this.chunkState;
    if (!src || !state || cx < 0 || cy < 0 || cx >= src.cols || cy >= src.rows) return;
    if (state[cy * src.cols + cx] === 2) return;
    // A neighbour's obstacles reach at most `spill` into this chunk, so the 3 by 3 block is enough.
    for (let ny = Math.max(0, cy - 1); ny <= Math.min(src.rows - 1, cy + 1); ny++) {
      for (let nx = Math.max(0, cx - 1); nx <= Math.min(src.cols - 1, cx + 1); nx++) {
        const n = ny * src.cols + nx;
        if ((state[n] ?? 0) > 0) continue;
        state[n] = 1;
        // Ranks after every plan obstacle, by chunk and then by place in the chunk.
        const base = (n + 1) * 2 ** 20;
        for (const [j, o] of src.obstacles(nx, ny).entries()) this.insert(o, base + j);
      }
    }
    state[cy * src.cols + cx] = 2;
    this.chunksBuilt++;
    const per = src.size / NAV.cellSize;
    this.fillWalkable(cx * per, cy * per, Math.min(this.navCols, (cx + 1) * per), Math.min(this.navRows, (cy + 1) * per));
  }

  /** Builds every chunk a rectangle touches. */
  private ensureRect(x0: number, y0: number, x1: number, y1: number): void {
    const src = this.source;
    // Every collision test comes through here; once the whole map is built it costs one compare.
    if (!src || this.chunksBuilt === src.cols * src.rows) return;
    const size = src.size;
    const cx0 = clamp(Math.floor(x0 / size), 0, src.cols - 1);
    const cy0 = clamp(Math.floor(y0 / size), 0, src.rows - 1);
    const cx1 = clamp(Math.floor(x1 / size), 0, src.cols - 1);
    const cy1 = clamp(Math.floor(y1 / size), 0, src.rows - 1);
    for (let cy = cy0; cy <= cy1; cy++) for (let cx = cx0; cx <= cx1; cx++) this.ensureChunk(cx, cy);
  }

  /** Builds every chunk, as if the map had been built whole. For tests and tools. */
  ensureAll(): void {
    const src = this.source;
    if (!src) return;
    for (let cy = 0; cy < src.rows; cy++) for (let cx = 0; cx < src.cols; cx++) this.ensureChunk(cx, cy);
  }

  /** Calls `visit` with every hash cell a shape's bounds touch. */
  private forCells(shape: Shape, visit: (cell: number) => void): void {
    const b = shapeBounds(shape);
    const cx0 = clamp(Math.floor(b.x0 / HASH_CELL), 0, this.cols - 1);
    const cy0 = clamp(Math.floor(b.y0 / HASH_CELL), 0, this.rows - 1);
    const cx1 = clamp(Math.floor(b.x1 / HASH_CELL), 0, this.cols - 1);
    const cy1 = clamp(Math.floor(b.y1 / HASH_CELL), 0, this.rows - 1);
    for (let cy = cy0; cy <= cy1; cy++) for (let cx = cx0; cx <= cx1; cx++) visit(cy * this.cols + cx);
  }

  private nearby(x: number, y: number, pad: number): Set<Obstacle> {
    this.ensureRect(x - pad, y - pad, x + pad, y + pad);
    return this.nearbyNow(x, y, pad);
  }

  /** The obstacles near a point among those already in the hash, without building any chunk. */
  private nearbyNow(x: number, y: number, pad: number): Set<Obstacle> {
    const out = new Set<Obstacle>();
    const cx0 = clamp(Math.floor((x - pad) / HASH_CELL), 0, this.cols - 1);
    const cy0 = clamp(Math.floor((y - pad) / HASH_CELL), 0, this.rows - 1);
    const cx1 = clamp(Math.floor((x + pad) / HASH_CELL), 0, this.cols - 1);
    const cy1 = clamp(Math.floor((y + pad) / HASH_CELL), 0, this.rows - 1);
    for (let cy = cy0; cy <= cy1; cy++) {
      for (let cx = cx0; cx <= cx1; cx++) for (const o of this.grid[cy * this.cols + cx] ?? []) out.add(o);
    }
    return out;
  }

  pointBlocked(x: number, y: number, radius: number, mask: CollisionMask): boolean {
    if (x < radius || y < radius || x > this.width - radius || y > this.height - radius) return true;
    this.ensureRect(x - radius, y - radius, x + radius, y + radius);
    return this.blockedNow(x, y, radius, mask);
  }

  /**
   * `pointBlocked` against the obstacles in the hash. Working out a chunk's nav cells uses it: every
   * obstacle that reaches a point of the chunk is already in, so it needs no other chunk built.
   */
  private blockedNow(x: number, y: number, radius: number, mask: CollisionMask): boolean {
    if (x < radius || y < radius || x > this.width - radius || y > this.height - radius) return true;
    for (const o of this.nearbyNow(x, y, radius)) {
      if ((mask === 'move' ? o.blocksMove : o.blocksShots) && shapeBlocks(o.shape, x, y, radius)) return true;
    }
    return false;
  }

  /**
   * Pushes a circle out of every blocking obstacle it overlaps, then clamps to the map. Sliding
   * falls out naturally: only the penetrating component of the motion is removed.
   */
  resolveCircle(pos: Vec2, radius: number, mask: CollisionMask = 'move'): Vec2 {
    let x = pos.x;
    let y = pos.y;
    for (let pass = 0; pass < RESOLVE_PASSES; pass++) {
      let moved = false;
      for (const o of this.nearby(x, y, radius)) {
        if (!(mask === 'move' ? o.blocksMove : o.blocksShots)) continue;
        const c = closest(o.shape, x, y);
        let dx = x - c.cx;
        let dy = y - c.cy;
        const reach = c.pad + radius;
        const d2 = dx * dx + dy * dy;
        if (!c.inside && d2 >= reach * reach) continue;
        let d = Math.sqrt(d2);
        if (c.inside) {
          // Inside a box: the closest face point is where we exit, pointing outward from the centre.
          dx = -dx;
          dy = -dy;
        }
        if (d < 1e-6) {
          // Dead centre has no direction; push along +x so the result stays deterministic.
          dx = 1;
          dy = 0;
          d = 1;
        }
        x = c.cx + (dx / d) * reach;
        y = c.cy + (dy / d) * reach;
        moved = true;
      }
      if (!moved) break;
    }
    return { x: clamp(x, radius, this.width - radius), y: clamp(y, radius, this.height - radius) };
  }

  /** True when a straight line between two points is clear of obstacles, inflated by `pad`. */
  lineClear(ax: number, ay: number, bx: number, by: number, pad: number, mask: CollisionMask): boolean {
    const len = Math.hypot(bx - ax, by - ay);
    const n = Math.max(1, Math.ceil(len / Math.max(16, pad)));
    for (let i = 1; i < n; i++) {
      const t = i / n;
      if (this.pointBlocked(ax + (bx - ax) * t, ay + (by - ay) * t, pad, mask)) return false;
    }
    return true;
  }

  /** Movement speed multiplier at a point: faster on roads and paths. */
  speedAt(x: number, y: number): number {
    const cx = clamp(Math.floor(x / HASH_CELL), 0, this.cols - 1);
    const cy = clamp(Math.floor(y / HASH_CELL), 0, this.rows - 1);
    for (const r of this.roadGrid[cy * this.cols + cx] ?? []) {
      const c = closest(r, x, y);
      if (c.inside || (x - c.cx) ** 2 + (y - c.cy) ** 2 <= c.pad * c.pad) return 1 + GROUND.roadSpeedBonus;
    }
    return 1;
  }

  navCell(x: number, y: number): number {
    const cx = clamp(Math.floor(x / NAV.cellSize), 0, this.navCols - 1);
    const cy = clamp(Math.floor(y / NAV.cellSize), 0, this.navRows - 1);
    return cy * this.navCols + cx;
  }

  isWalkable(cx: number, cy: number): boolean {
    if (cx < 0 || cy < 0 || cx >= this.navCols || cy >= this.navRows) return false;
    const i = cy * this.navCols + cx;
    // Only a built chunk has open cells, so an open cell needs no more checks: the flow field
    // asks this eight times per cell it searches.
    if (this.walkable[i] === 1) return true;
    const src = this.source;
    if (!src || !this.chunkState) return false;
    const per = src.size / NAV.cellSize;
    const k = Math.floor(cx / per);
    const j = Math.floor(cy / per);
    if (this.chunkState[j * src.cols + k] === 2) return false;
    this.ensureChunk(k, j);
    return this.walkable[i] === 1;
  }

  /** Nearest free spot to (x, y), searching outward in rings. Used for spawns and portal arrivals. */
  findOpen(x: number, y: number, radius: number): Vec2 {
    if (!this.pointBlocked(x, y, radius, 'move')) return { x, y };
    for (let ring = 1; ring < 40; ring++) {
      const d = ring * 20;
      const steps = 8 + ring * 2;
      for (let k = 0; k < steps; k++) {
        const a = (Math.PI * 2 * k) / steps;
        const px = x + Math.cos(a) * d;
        const py = y + Math.sin(a) * d;
        if (!this.pointBlocked(px, py, radius, 'move')) return { x: px, y: py };
      }
    }
    return { x, y };
  }
}
