import { CHUNK_DECOR_ASSETS, DEFAULT_TOWN_LAYOUT, layoutToMap, scaledZone } from '@rune/shared';
import { BoxGeometry, Group, InstancedMesh, Material, Mesh, MeshBasicMaterial, Texture, type Object3D } from 'three';
import { beforeAll, describe, expect, it } from 'vitest';
import { streamRadii } from '../src/render/chunks.js';
import { buildWorld, isLitDecor } from '../src/render/props.js';
import { WorldChunks } from '../src/render/worldChunks.js';

describe('a zone generated by chunk on the client', () => {
  it('registers a chunk and its neighbours before the chunk is first built, and nothing far away', () => {
    const chunks = new WorldChunks();
    const filled: number[] = [];
    const built: string[] = [];
    // Five chunks in a row; each fill puts a piece in its own chunk and one just over its east edge.
    for (let cx = 0; cx < 5; cx++) {
      chunks.lazy(cx, 0, () => {
        filled.push(cx);
        chunks.build(cx * 1000 + 500, 500, 0, () => built.push(`${cx} own`));
        chunks.build(cx * 1000 + 1100, 500, 0, () => built.push(`${cx} spill`));
      });
    }
    const r = streamRadii(600);
    expect(filled).toEqual([]);
    chunks.update(0, 500, 500, r);
    // Chunks 0 and 1 are in view and built at once, chunk 2 by the prefetch: each had its own and
    // its neighbours' content registered first, so chunk 3 is filled and chunk 4 is not.
    expect(chunks.stats.built).toBe(3);
    expect(filled).toEqual([0, 1, 2, 3]);
    expect(built.sort()).toEqual(['0 own', '0 spill', '1 own', '1 spill', '2 own']);
    expect(chunks.stats.filled).toBe(4);
    // Walk to the far end: everything is filled once and every piece built in its own chunk.
    for (let x = 500; x <= 4500; x += 250) for (let k = 0; k < 4; k++) chunks.update(0, x, 500, r);
    expect([...filled].sort()).toEqual([0, 1, 2, 3, 4]);
    expect(built).toContain('3 spill');
    expect(built).toContain('4 own');
    chunks.dispose();
  });

  it('the decor chunks scatter is never a light or a fire, since a world\'s light budget is set at load', () => {
    expect(CHUNK_DECOR_ASSETS.length).toBeGreaterThan(0);
    for (const asset of CHUNK_DECOR_ASSETS) {
      expect(isLitDecor(asset), asset).toBe(false);
      expect(['campfire', 'brazier']).not.toContain(asset);
    }
  });
});

describe('world chunks free what they own', () => {
  it('disposes instanced geometry a builder made, on release and on dispose, and a landmark\'s on dispose', () => {
    const chunks = new WorldChunks();
    const shared = new BoxGeometry(1, 1, 1);
    chunks.shared.add(shared);
    let builds = 0;
    let freed = 0;
    let sharedFreed = 0;
    shared.addEventListener('dispose', () => sharedFreed++);
    chunks.build(500, 500, 0, (g) => {
      builds++;
      // Like a bridge's planks: an instanced mesh over geometry of its own.
      const geo = new BoxGeometry(1, 1, 1);
      geo.addEventListener('dispose', () => freed++);
      g.add(new InstancedMesh(geo, new MeshBasicMaterial(), 3), new InstancedMesh(shared, new MeshBasicMaterial(), 2));
    });
    // Like a camp fire's stones: built once, kept across releases.
    const fireGeo = new BoxGeometry(1, 1, 1);
    let fireFreed = 0;
    fireGeo.addEventListener('dispose', () => fireFreed++);
    const fire = new Group();
    fire.add(new InstancedMesh(fireGeo, new MeshBasicMaterial(), 9));
    chunks.attach(500, 500, 60, fire);
    const r = streamRadii(600);
    chunks.update(0, 500, 500, r);
    chunks.update(0, 50000, 50000, r);
    expect(chunks.stats.releases).toBe(1);
    expect(freed).toBe(1);
    expect(fireFreed).toBe(0);
    chunks.update(0, 500, 500, r);
    chunks.update(0, 50000, 50000, r);
    chunks.dispose();
    expect(builds).toBe(2);
    expect(freed).toBe(2);
    expect(fireFreed).toBe(1);
    expect(sharedFreed).toBe(0);
  });
});

/** Every texture and material the meshes under `root` use. */
function resources(root: Object3D): { textures: Set<Texture>; materials: Set<Material> } {
  const textures = new Set<Texture>();
  const materials = new Set<Material>();
  root.traverse((o) => {
    if (!(o instanceof Mesh)) return;
    for (const m of Array.isArray(o.material) ? o.material : [o.material]) {
      if (!(m instanceof Material)) continue;
      materials.add(m);
      for (const v of Object.values(m)) if (v instanceof Texture) textures.add(v);
    }
  });
  return { textures, materials };
}

describe('a built world', () => {
  beforeAll(() => {
    // The procedural textures draw on canvases; blank ones are enough to build the scene graph.
    if (typeof document === 'undefined') Object.assign(globalThis, { document: { createElement: () => ({ width: 0, height: 0, getContext: () => null }) } });
  });

  it('frees every texture and material it made when disposed, as the town editor rebuilds it on every edit', () => {
    const def = layoutToMap(DEFAULT_TOWN_LAYOUT);
    const make = () => {
      const w = buildWorld(def);
      // Zoomed far out, so every chunk of the town is built.
      w.update(0, def.width / 2, def.height / 2, 6000);
      return w;
    };
    const a = make();
    const used = resources(a.group);
    expect(used.textures.size).toBeGreaterThan(3);
    const freed = new Set<unknown>();
    for (const t of used.textures) t.addEventListener('dispose', () => freed.add(t));
    for (const m of used.materials) m.addEventListener('dispose', () => freed.add(m));
    a.dispose();
    const b = make();
    const again = resources(b.group);
    // What a rebuild uses again is shared on purpose (portal swirls and fire embers, prop models);
    // everything else the first world made is freed.
    for (const t of used.textures) if (!again.textures.has(t)) expect(freed.has(t), `texture ${t.uuid}`).toBe(true);
    const keptMaterials = [...used.materials].filter((m) => !again.materials.has(m) && !freed.has(m));
    // Trees and lights keep per-world materials that hold no textures of their own; none of them has a map.
    for (const m of keptMaterials) for (const v of Object.values(m)) if (v instanceof Texture) expect(again.textures.has(v) || freed.has(v)).toBe(true);
    b.dispose();
  });

  it('generates a zone\'s chunks only as the camera nears them', () => {
    const { def, zone } = scaledZone('thornwood', 11, 3);
    const w = buildWorld(def, zone);
    expect(zone.generatedChunks).toBe(0);
    w.update(0, def.spawn.x, def.spawn.y, 600);
    const total = zone.cols * zone.rows;
    expect(w.stats.filled).toBeGreaterThan(0);
    expect(w.stats.filled).toBeLessThan(total / 4);
    expect(zone.generatedChunks).toBeLessThan(total / 2);
    w.dispose();
  });
});
