// Writes packages/shared/src/world/townDecorAssets.ts: every asset the town editor can place, with
// its footprint at scale 1 measured from the model file at its registered height (assets.ts). The
// server checks saved towns against this list and builds collision for decor marked solid, so it
// has to know sizes without loading three.js models.
// Usage: apps/server/node_modules/.bin/tsx scripts/assets/town-decor.ts (after changing assets.ts)
import { getBounds, NodeIO } from '@gltf-transform/core';
import { writeFileSync } from 'node:fs';
import { ASSETS, type AssetDef } from '../../apps/client/src/render/assets.js';
import { isLitDecor, PROCEDURAL_DECOR } from '../../apps/client/src/render/props.js';

const OUT = 'packages/shared/src/world/townDecorAssets.ts';
type Shape = 'box' | 'round' | 'trunk';

interface Row {
  id: string;
  w: number;
  d: number;
  ox: number;
  oz: number;
  h: number;
  shape: Shape;
  solid: boolean;
  lit: boolean;
}

/** Trees collide at the trunk; round things with a circle; everything else with its box. */
function shapeOf(id: string): Shape {
  if (/^(tree_single_[AB]|grave_tree_dead_)/.test(id) && !id.endsWith('_cut')) return 'trunk';
  if (/^(trees_|hills?_|mountain_|rock_single|barrel|bucket|building_well|campfire|brazier|tree_single|dungeon_(pillar|column|barrel)|grave_(pillar|candle|skull|shrine))/.test(id)) return 'round';
  return 'box';
}

/**
 * Whether a newly placed piece blocks walking; builders can change it per piece. Buildings, walls
 * and big clutter block; openings (gates, doorways, arches), flat pieces, cloth and clutter a
 * hero steps round in a real town do not.
 */
function solidOf(def: { id: string; category: string }, w: number, d: number, h: number): boolean {
  const id = def.id;
  if (/gate$|_gate_|doorway|arch|bridge|building_grain|building_stage_A|floor_|path_|pallet|banner|flag|water|_cut$|bed_floor|weaponrack/.test(id)) return false;
  if (def.category === 'building' || def.category === 'wall') return true;
  if (def.category === 'nature') return /^(trees_|tree_single|grave_tree_dead|hills_|hill_single_C|mountain_)/.test(id);
  return h >= 25 && Math.max(w, d) >= 30;
}

const round = (v: number): number => Math.round(v * 10) / 10;
const io = new NodeIO();
const rows: Row[] = [];
const placeable = ASSETS.filter((a: AssetDef) => a.category !== 'hero' && a.category !== 'monster' && a.town !== false);
for (const def of placeable) {
  const doc = await io.read(`apps/client/public${def.url}`);
  const scene = doc.getRoot().getDefaultScene() ?? doc.getRoot().listScenes()[0];
  if (!scene) throw new Error(`${def.id}: no scene`);
  const b = getBounds(scene);
  const fit = def.height / (b.max[1] - b.min[1]);
  const w = (b.max[0] - b.min[0]) * fit;
  const d = (b.max[2] - b.min[2]) * fit;
  rows.push({ id: def.id, w: round(w), d: round(d), ox: round(((b.max[0] + b.min[0]) / 2) * fit), oz: round(((b.max[2] + b.min[2]) / 2) * fit), h: def.height, shape: shapeOf(def.id), solid: solidOf(def, w, d, def.height), lit: isLitDecor(def.id) });
}
// The fires are built in code; their footprints are the stone ring and the tripod.
const PROCEDURAL_SIZE: Record<string, number> = { campfire: 54, brazier: 32 };
for (const [id, p] of Object.entries(PROCEDURAL_DECOR)) {
  const s = PROCEDURAL_SIZE[id] ?? 30;
  rows.push({ id, w: s, d: s, ox: 0, oz: 0, h: p.height, shape: 'round', solid: false, lit: isLitDecor(id) });
}
rows.sort((a, b) => a.id.localeCompare(b.id));

const body = rows.map((r) => `  ${r.id}: { w: ${r.w}, d: ${r.d}, ox: ${r.ox}, oz: ${r.oz}, h: ${r.h}, shape: '${r.shape}', solid: ${r.solid}, lit: ${r.lit} },`).join('\n');
writeFileSync(
  OUT,
  `// Generated by scripts/assets/town-decor.ts from the client's asset registry; do not edit by hand.

/**
 * An asset the town editor can place. Sizes are world units at scale 1: the footprint (w along the
 * model's x, d along its z), the footprint's centre offset from the model's origin, and the height.
 */
export interface TownDecorSpec {
  w: number;
  d: number;
  ox: number;
  oz: number;
  h: number;
  /** The collision shape when placed solid: its box, a circle, or just the trunk of a tree. */
  shape: 'box' | 'round' | 'trunk';
  /** Whether a newly placed one blocks walking; each placed piece can change it. */
  solid: boolean;
  /** A lamp or flame, which costs a light and a fire. */
  lit: boolean;
}

export const TOWN_DECOR_ASSETS: Readonly<Record<string, TownDecorSpec>> = {
${body}
};
`,
);
console.log(`${rows.length} placeable assets written to ${OUT}`);
